# Generated by Django 4.0.6 on 2022-08-01 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office', '0003_patient_dob_patient_heartrate_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(1957, 6, 6, 0, 0)),
        ),
    ]
